name: inventario_app
description: "Sistema de inventario con sincronización web y móvil"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # ✅ GESTIÓN DE ESTADO
  provider: ^6.0.5
  # ✅ BASE DE DATOS
  sqflite: ^2.3.0
  path: ^1.8.3
  # ✅ PICKER DE ARCHIVOS E IMÁGENES - ALTERNATIVA COMPATIBLE
  image_picker: ^0.8.9                    # ← NUEVA ALTERNATIVA
  photo_view: ^0.14.0
   # ✅ QR
  qr_flutter: ^4.0.0
  # ✅ PDF E IMPRESIÓN
  printing: ^5.9.2
  pdf: ^3.10.4
  open_file: ^3.3.1
  # ✅ EXCEL
  excel: ^2.0.1
  #Google API's
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
 # ✅ UTILIDADES
  intl: ^0.17.0
  path_provider: ^2.1.1
  # ✅ PERMISOS
  permission_handler: ^11.0.1
  file_picker: ^5.5.0
  # ✅ BASE DE DATOS WINDOWS
  sqflite_common_ffi: ^2.3.6
  # ✅ ICONOS
  cupertino_icons: ^1.0.8
  #flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# ✅ SPLASH SCREEN CONFIGURATION
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true

# ✅ LAUNCHER ICONS CONFIGURATION
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#02569B"
    theme_color: "#02569B"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_white.png
    - assets/images/splash.png
    - assets/images/icon.png