// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM_KZd069XPTAd9bYxNA-PrTh3fZKwO6o',
    appId: '1:227690024935:web:d5d1310d93fdd20f5eb742',
    messagingSenderId: '227690024935',
    projectId: 'invapp-5f0f9',
    authDomain: 'invapp-5f0f9.firebaseapp.com',
    storageBucket: 'invapp-5f0f9.firebasestorage.app',
    measurementId: 'G-7B7TZWRE2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5SKsDOb2rHMR5JOM1oa2bfRzX6FkIjfc',
    appId: '1:227690024935:android:e0091076bf24dde35eb742',
    messagingSenderId: '227690024935',
    projectId: 'invapp-5f0f9',
    storageBucket: 'invapp-5f0f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI5hnX6x5EXVZoey26xYM-6CXfidA-gi0',
    appId: '1:227690024935:ios:7c32a7a9a78b61855eb742',
    messagingSenderId: '227690024935',
    projectId: 'invapp-5f0f9',
    storageBucket: 'invapp-5f0f9.firebasestorage.app',
    iosBundleId: 'com.example.inventapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM_KZd069XPTAd9bYxNA-PrTh3fZKwO6o',
    appId: '1:227690024935:web:ea643a8bf27351df5eb742',
    messagingSenderId: '227690024935',
    projectId: 'invapp-5f0f9',
    authDomain: 'invapp-5f0f9.firebaseapp.com',
    storageBucket: 'invapp-5f0f9.firebasestorage.app',
    measurementId: 'G-SNZ8DN4JK6',
  );

}